=== inf22tig08/WebM1/xmlFiles/contacto.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="animales">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="informacion" type="informacionType"/>
        <xs:element name="contacto" type="contactoType" maxOccurs="2"/>
        <xs:element name="redes_sociales" type="redesSocialesType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="informacionType">
    <xs:sequence>
      <xs:element name="titulo" type="xs:string"/>
      <xs:element name="descripcion" type="xs:string"/>
      <xs:element name="autor" type="xs:string"/>
      <xs:element name="fecha" type="xs:date"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="contactoType" >
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="email" type="xs:string"/>
      <xs:element name="telefono" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="redesSocialesType">
    <xs:sequence>
      <xs:element name="red_social" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="enlace" type="xs:anyURI"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== inf22tig08/WebM1/xmlFiles/contacto.xml
<?xml version="1.0" encoding="UTF-8"?>
<animales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="contacto.xsd">
  <informacion>
    <titulo>Bienvenido a la p√°gina de Animales en peligro de extincion</titulo>
    <descripcion>Descubre el fascinante mundo de los animales en extincion y como darse cuenta de su importancia.</descripcion>
    <autor>Jesus Reyes de Toro y Rafael Fernandez Nevado</autor>
    <fecha>2023-06-11</fecha>
  </informacion>
  
  <contacto>
    <nombre>Jesus Reyes de Toro</nombre>
    <email>reyesdetoro@gmail.com</email>
    <telefono>601245689</telefono>
  </contacto>

   <contacto>
    <nombre>Rafaell Fernandez Nevado</nombre>
    <email>rafaelfernandeznev@gmail.com</email>
    <telefono>671456719</telefono>
  </contacto>
  
  
  <redes_sociales>
    <red_social>
      <nombre>Facebook</nombre>
      <enlace>https://www.facebook.com/</enlace>
    </red_social>
    <red_social>
      <nombre>Twitter</nombre>
      <enlace>https://www.twitter.com/ejemplo</enlace>
    </red_social>
    <red_social>
      <nombre>GitHub</nombre>
      <enlace>https://www.instagram.com/ejemplo</enlace>
    </red_social>
  </redes_sociales>
</animales>
